### PR TITLE
Scaffold front page

### PR DESCRIPTION
**Pull request by mikeyrayvon**

### CODE REVIEW

**Comment by mixcas** [comment]
IMO using it's better to use WP_Query instead of get_post

For now, on the left side we are getting the latest projects and in the right side the oldest projects. We need confirmation of this works, otherwise we would do double work.

**Comment by mikeyrayvon** [comment]
wp_query better in what way?

confirmation that the scrolling works or the markup or what? 

maybe you want to build your scrolling stuff into this branch instead of merging it?

**Comment by mixcas** [comment]
I think WP_Query syntax is nicer and more readable because is similar to the default loop. I mean, using `has_posts()`, `the_post()`, etc.
IMO get_posts should be used only when getting posts in an Array form offers some benefit.
Performance wise they are almost the same, get_posts is a wrapper for WP_Query.

Confirmation of what posts are the output here. With the code as it is we would be outputting the latest posts on the left and the oldest ones in the right. The oldest ones are going to be always the same. I really don't think this is the desired behaviour.

I'm just guessing here but maybe is the latest posts with their respective side picture (left or right) in both columns just ordered in opposite ways.

No, the scrolling stuff would go in a different branch.

**Comment by mikeyrayvon** [comment]
OK i just emailed Emilio about what posts we should output here.

**Review by mixcas — CHANGES_REQUESTED** [review]
Let's check with the client (testing github's new review features)

**Comment by mikeyrayvon** [comment]
ok emilio says 5 recent is good

**Pull request merged**
